### ISSUE TITLE
error: variable cExpectedResult’ has initializer but incomplete type

### ISSUE THREAD

**Issue by JackChen080808** [langroodi/Adaptive-AUTOSAR#34]
/home/jack/codebase/Adaptive-AUTOSAR/build/_deps/doip-lib-src/test/routing_activation_request_test.cpp: In member function ‘virtual void DoipLib::RoutingActivationRequestTest_SerializationWithoutOemData_Test::TestBody()’:
/home/jack/codebase/Adaptive-AUTOSAR/build/_deps/doip-lib-src/test/routing_activation_request_test.cpp:14:51: error: variable ‘const std::array<unsigned char, 15> cExpectedResult’ has initializer but incomplete type
   14 |         const std::array<uint8_t, cPayloadLength> cExpectedResult{

The info aboval shows the detail of the error. Please help give solution.

THanks
Jack

**Comment by JackChen080808** [comment]
the compiler is gcc 13.2.0

**Comment by langroodi** [comment]
The error is not related to this project but the [DoIP-Lib](https://github.com/langroodi/DoIP-Lib) project. Because the mentioned compiler is not supported, I only can assume that including `<array>` header at `routing_activation_request_test.cpp` in that project may solve the issue. Further than that, I cannot help anymore.

**Comment by JackChen080808** [comment]
Yes, it belongs to DoIP project. Thanks a lot for support and help. Although it seems not to work with including <array>

**Comment by JackChen080808** [comment]
with include array.
